services:
  opa:
    image: openpolicyagent/opa:0.40.0-rootless
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "--set=services.nginx.url=http://bundle_server"
      - "--set=bundles.nginx.service=nginx"
      - "--set=bundles.nginx.resource=bundle.tar.gz"
      - "--set=bundles.nginx.polling.min_delay_seconds=10"
      - "--set=bundles.nginx.polling.max_delay_seconds=30"
    depends_on:
      - bundle_server
    networks:
      - default
      - integrations

  api_server:
    image: openpolicyagent/demo-restful-api:0.2
    ports:
      - "5000:5000"
    environment:
      - OPA_ADDR=http://opa:8181
      - POLICY_PATH=/v1/data/httpapi/authz
    depends_on:
      - opa

  bundle_server:
    image: nginx:1.20.0-alpine
    ports:
      - 8888:80
    volumes:
      - ./bundle.tar.gz:/usr/share/nginx/html/bundle.tar.gz:ro

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.81.0
    hostname: otel-collector
    restart: always
    command: [ "--config=/conf/collector.yaml" ]
    volumes:
      - ./collector.yaml:/conf/collector.yaml:ro
    environment:
      LS_ACCESS_TOKEN: "${LS_ACCESS_TOKEN}"
    depends_on:
      - opa
    networks:
      - integrations

networks:
  integrations:
